### ISSUE TITLE
insertToken URL check

### ISSUE THREAD

**Issue by vtforester** [djarrard-zz/WebmapWrappers#2]
Seems like the `if` statement logic is backwards on [line #68](https://github.com/djarrard/WebmapWrappers/blob/master/InsertToken/addtoken.py#L68). 

``` python
if serviceBaseUrl in serverBaseUrl:
```

should be

``` python
if serverBaseUrl in serviceBaseUrl:
```

This is how it's written on [line #55](https://github.com/djarrard/WebmapWrappers/blob/master/InsertToken/addtoken.py#L55)

**Comment by djarrard-zz** [comment]
Good catch, @vtforester! I appreciate you letting me know. I have made the change in the code and will go ahead and close this issue out. Did you run into this while using the wrapper or did you just spot it while looking through the code?

**Comment by vtforester** [comment]
No problem, we're actually using the code with a few modifications. Our client has some pretty specific scenarios that would prevent us from merging but we definitely appreciate the workaround. One update that might be nice in _this_ repo is to have an optional parameter for the token service URL so there's one less request to the info endpoint.

We _have_ heard, however, that the issue (#NIM094431) should be fixed in v10.3 of ArcGIS Server.

**Comment by djarrard-zz** [comment]
I actually initially had this code configured to where the Token URL was provided by the user, but I decided to automate it in one of my recent updates. The reason is that if HTTPS is configured on ArcGIS for Server, the token URL provided at the Info page is provided in HTTPS. I didn't want for users to provide an HTTP token URL if HTTPS was available. In other words, I wanted users to authenticate over a secure channel if at all possible. Otherwise, the username and password are sent in plain text. Since a call to the Info page call _usually_ takes a couple tenths of a second, I felt it was worth the tradeoff.

I've also heard that the bug is fixed, but it doesn't look like Esri has released any official notes on that quite yet. I hope it is fixed. It'll make my getToken wrapper a bit more irrelevant in most cases but at least the replaceServicePaths will still be useful :).

**Comment by Minson2000** [comment]
Thanks for the work around.  How would we configure so that we could enter the Input_JSON dynamically from the web map?  I can't seem to figure a way to make that default parameter blank.  Like in the basic printing tool service Thanks!

Description: A JSON representation of the state of the map to be exported as it appears in the web application. See the WebMap specification in the ArcGIS Help to understand how this text should be formatted. The ArcGIS web APIs (for JavaScript, Flex, Silverlight, etc.) allow developers to easily get this JSON string from the map. 
Default Value:

**Comment by green3g** [comment]
I think you just need to rename the `Input_JSON` parameter to `Web_Map_As_JSON` to match the spec of the original print task.

From: http://resources.arcgis.com/en/help/main/10.2/index.html#//0154000005z2000000
Caution:
The Web_Map_as_JSON, Format, Layout_Template, and Output_File parameter names must be spelled exactly as shown so they match the tool signature of the Print Task in the ArcGIS web APIs. For more information on the parameters, see Export Web Map. The Georef_info parameter is an extra parameter that will be passed to the Print Task and therefore has no naming convention to conform to.

**Comment by djarrard-zz** [comment]
@roemhildtg, that's actually a good point on @Minson2000 's question. It looks like @Minson2000 may have duplicated his question, as I've already responded to this at #3. I think his question was more along the lines of how to make the default parameter value in REST blank, but what you brought up represents a potential problem for folks who are using the Print widgets that are built into the Flex, Silverlight, and Javascript APIs. In most of my testing, I hooked up the print service to a geoprocessing widget (instead of a print widget) so I didn't see any problems. I'm going to fix this.

**Comment by Minson2000** [comment]
Thanks for your reply!

Do you have an example of javascript code?

We are using the print widget tool and we are still having issues.

This line of code when we add it to the web map as a JSON field, it break
and there is no detailed error stacktrace.

{"id":"layer10","title":"layer10","opacity":1,"minScale":0,"maxScale":0,"token":"*********_","url":"https:
*
<http://gis**__dev.city_**_.org/ags**_/rest/services/utility/ex_utility/MapServer>
*********************************","visibleLayers":null,"layers":[]}
